TAR1090_URL: "http://localhost/data/aircraft.json"
TAR1090_INTERVAL: 3
DISCORD_WEBHOOK_URL: "DISCORD_WEBHOOK_URL"
RE_NOTICE_MINUTE: 30.0
CHECK_FLIGHTS:
  - SKY183
  - SKY185
  - SKY187
  - SKY791
  - SKY795
  - SKY831
  - SKY531
